name: planet_info
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.3
  google_sign_in: ^6.1.0
  flutter_signin_button: ^2.0.0
  google_generative_ai: ^0.4.7
  cloud_firestore: ^6.1.0
  cached_network_image: ^3.4.1
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  chat_bubbles: ^1.7.0
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_image.jpg
    - assets/Google_Gemini_Logo.png
    - assets/gemini_icon.webp
    - assets/gemini_logo.png
    - assets/solar_system.jpeg
    - assets/secrets.json
    - assets/planets/
    - assets/moons/
    - assets/stars/
    - assets/universe/
